### ISSUE TITLE
版本1.1.7 (25) ，mac最新系统，打开nas上通过smb共享的图片，放大后，拖动会返回原位

### ISSUE THREAD

**Issue by oloey** [kzhiquan/Picview-macOS#2]
用app store和网站下载的dmg安装都是一样的问题，打开本地图片不会有这种问题。

**Comment by kzhiquan** [comment]
你好，1.1.2版本中应该修复了这个问题，麻烦确认下，多谢。

**Comment by oloey** [comment]
> 你好，1.1.2版本中应该修复了这个问题，麻烦确认下，多谢。

确认修复了，感谢！
