### ISSUE TITLE
[需求]希望增加拷贝图像中文本操作的快捷键

### ISSUE THREAD

**Issue by gujin03** [kzhiquan/Picview-macOS#3]
具体使用的场景是这样的：
当在电脑上打开一些图片，图片当中有文本内容需要进行复制的时候，当前只能通过鼠标右键的方式去进行操作，希望可以添加快捷键，这样可以大大的提升操作效率
<img width="815" alt="image" src="https://github.com/kzhiquan/Picview-macOS/assets/38389059/47a972a5-09ac-41f5-a337-24d8423c39ff">

**Comment by kzhiquan** [comment]
Ctrl + C / Ctrl + V能解决这个问题。
