### ISSUE TITLE
[bug]状态栏遮挡了文字识别的按钮

### ISSUE THREAD

**Issue by gujin03** [kzhiquan/Picview-macOS#4]
请作者修复一下这个bug（确实非常影响使用体验），当选择文本的时候被状态栏遮挡从而无法操作。
![iShot_2024-01-20_17 03 57](https://github.com/kzhiquan/Picview-macOS/assets/38389059/da394561-dbd3-4b31-86d4-365185fbfef0)

**Comment by kzhiquan** [comment]
你好，1.2.2 版本中，已经对该问题进行了优化，请更新使用。

**Comment by gujin03** [comment]
因为我购买的是umas版本，有劳提供下载链接，谢谢。

**Comment by kzhiquan** [comment]
@gujin03 已经可以同步了，软件内有自动更新提醒。
